apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pipe
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka-server-kafka-brokers:9092"
    - name: consumerGroup
      value: "group1"
    - name: authRequired
      value: "false"
    - name: topics
      value: "sample-topic"
    - name: publishTopic
      value: "sample-topic"
